### ISSUE TITLE
[Error] Part of speech: null

### ISSUE THREAD

**Issue by EPadronU** [fedeztk/got#11]
When a word has no "part of a speech" information, `Part of speech: null` is shown. For example:

```bash
❯ got -o -f es -t en "ah"
Translated text: ah

Part of speech: null

Definition:
- Indica que el que habla se ha dado cuenta de algo o lo ha comprendido.
Use in sentence:
- ¡ah!, entonces tú no estabas

Definition:
- Indica admiración, sorpresa o pena.
Use in sentence:
- ¡ah!, ¿sí?

Definition:
- Indica satisfacción o alegría.
Use in sentence:
- ¡ah, qué bien lo pasábamos entonces!

Definition:
- Se utiliza para advertir de algo o para decir algo que se había olvidado
Use in sentence:
- ah, y no se lo digas a nadie que todavía no es seguro


Part of speech: interjection

- Ha!: ¡Ah!
- Ahoy!: ¡Ah!
```

- Engine: Google
- Version: 2a5b336c (`got -v` don't show a thing. since I just installed I could assume I have the last current commit)

**Comment by fedeztk** [comment]
[This](https://github.com/fedeztk/got/issues/12#issuecomment-1126703238) comment applies also in this case.
However here I can substitute the `null` part with something else (or just leave it empty).
If you have any suggestion in this regard I'll happily implement it.

**Comment by EPadronU** [comment]
Thank you for given a look to this. Maybe the `Part of speech` _heading_ could be completely omitted when `null` is provided by the engine. What do you think?

**Comment by fedeztk** [comment]
I too was thinking about something like this, but I noticed that it could potentially be misleading since one can interpret a translation as some other part of speech.
E.g. if a word has multiple definition/translation based on different context, by omitting one header it could led to think that all translations belongs to the same part of speech, which is incorrect since it is instead undefined.
I hope it is clear enough.

IMO there are 2 viable options, both of which leave the header:
- omit part of speech
- use undefined or similar concepts to let the user know that the part of speech is not specified

**Comment by EPadronU** [comment]
I see. `undefined` sounds like a good approach then.
