### ISSUE TITLE
Strip decorations for the oneshot mode?

### ISSUE THREAD

**Issue by 097115** [fedeztk/got#3]
When using `got` in the oneshot mode with `-o`, it would made sense to disable coloring and indenting the output as well as the `Translated text:` prefix in case the result will get passed to some other program, script, filter or pager.

May be adding some "stricter" oneshot mode is worth considering, like with `-O`, for instance? :)

**Comment by fedeztk** [comment]
For scripting IMHO it would be better to just directly `curl` simplytranslate's APIs and get the json, e.g. like:
```sh
  curl "https://simplytranslate.org/api/translate/?engine=google&from=it&to=en&text=ciao"
```
This because I don't see any benefit from the use of the raw output unless structured. I can provide a method that returns the json output so it can be used with tools like `jq`, making it easier for scripting.
If that doesn't cover your use case I may consider adding a raw print, I just need your feedback on this.

**Comment by 097115** [comment]
Yeah, `curl` is fine, indeed. Thanks.
