### ISSUE TITLE
Please make colors configurable

### ISSUE THREAD

**Issue by euneuber** [fedeztk/got#5]
Hi,

I like your tool -- it is very hand in "simple" environments!

I only have some troubles with the (pre)selected colors:
![grafik](https://user-images.githubusercontent.com/3296589/166494932-7da4b49a-9a91-451e-a119-c2753f47c8ab.png)

Please make them configurable in `.config/got/config.yml`

**Comment by fedeztk** [comment]
Thanks for the idea! Right now it pulls ANSI colors from your terminal colorscheme, but I certainly will make them configurable.

**Comment by fedeztk** [comment]
Since I had some time I did some tests with various light & dark colorschemes and I never experienced something like this. `got` pulls ANSI colors in a sensible manner. It is probably just a better idea to "correct" the colors. By that I mean just to set in your terminal emulator of choice a "better" black (generally color 0)

Just as an example, with two colorschemes that use the same color for the background and color 0, text is completely readable:
![image](https://user-images.githubusercontent.com/58485208/174339267-3bdcf530-05ad-45b0-a8d6-a1007707cae8.png)
![image](https://user-images.githubusercontent.com/58485208/174340358-8dd11186-6534-4c3e-a8cf-9c7f51ac02fa.png)

If you agree on that, please close the issue.

**Comment by fedeztk** [comment]
I'll temporarily close this due to inactivity/lack of feedback, but feel free to reopen if the issue is still happening in the future.
